=== OpenBEL/openbel-framework-resources/index.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!-- BELFramework index file, version 1.0 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
    attributeFormDefault="qualified"
    targetNamespace="http://www.belscript.org/schema/index"
    xmlns:idx="http://www.belscript.org/schema/index">

    <!-- Top-level index element. -->
    <xs:element name="index">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="idx:annotationdefinitions" minOccurs="1" />
                <xs:element ref="idx:namespaces" minOccurs="1" />
                <xs:element ref="idx:equivalences" minOccurs="1" />
                <xs:element ref="idx:knowledge" minOccurs="1" />
            </xs:sequence>
            <xs:attribute name="belframework_version" use="required" type="xs:string" />
        </xs:complexType>

        <xs:key name="namespaceKEY">
            <xs:selector xpath="./idx:namespaces/idx:namespace"/>
            <xs:field xpath="@idx:resourceLocation"/>
        </xs:key>

        <xs:keyref name="namespaceKEYREF" refer="idx:namespaceKEY">
            <xs:selector xpath=".//idx:namespace-ref"/>
            <xs:field xpath="@idx:resourceLocation"/>
        </xs:keyref>
    </xs:element>

    <xs:element name="annotationdefinitions">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="idx:annotationdefinition" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="namespaces">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="idx:namespace" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="equivalences">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="idx:equivalence" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="knowledge">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="idx:protein-families" minOccurs="0" maxOccurs="1" />
                <xs:element ref="idx:named-complexes" minOccurs="0" maxOccurs="1" />
                <xs:element ref="idx:gene-scaffolding" minOccurs="0" maxOccurs="1" />
                <xs:element ref="idx:orthologies" minOccurs="0" maxOccurs="1" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="annotationdefinition" type="idx:resourceContent" />

    <xs:element name="namespace" type="idx:resourceContent" />

    <xs:element name="equivalence">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="idx:namespace-ref" />
            </xs:sequence>
            <xs:attribute name="resourceLocation" use="required" type="idx:resourceLocation" />
        </xs:complexType>
    </xs:element>

    <xs:element name="namespace-ref" type="idx:resourceContent" />

    <xs:element name="target-namespace" type="idx:resourceContent" />

    <xs:element name="protein-families" type="idx:resourceContent" />

    <xs:element name="named-complexes" type="idx:resourceContent" />

    <xs:element name="gene-scaffolding" type="idx:resourceContent" />

    <xs:element name="orthologies">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="idx:orthology" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="orthology" type="idx:resourceContent" />

    <!-- Types -->
    <xs:complexType name="resourceContent">
        <xs:attribute name="resourceLocation" use="required" type="idx:resourceLocation" />
    </xs:complexType>

    <xs:simpleType name="resourceLocation">
        <xs:restriction base="xs:anyURI" />
    </xs:simpleType>
</xs:schema>

=== OpenBEL/openbel-framework-resources/ORTHOLOGY/index.xml
<idx:index
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.belscript.org/schema/index index.xsd"
    xmlns:idx="http://www.belscript.org/schema/index"
    idx:belframework_version="1.0">

    <!--
        BEL Framework V1.4.0 Resource Index
        Last Updated: 4/26/2012

        Copyright (c) 2011-2012, Selventa. All Rights Reserved.
    -->

    <idx:annotationdefinitions>
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/atcc-cell-line.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-body-region.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-cardiovascular-system.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-cell.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-cell-structure.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-digestive-system.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-disease.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-embryonic-structure.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-endocrine-system.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-fluid-and-secretion.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-hemic-and-immune-system.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-integumentary-system.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-musculoskeletal-system.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-nervous-system.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-respiratory-system.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-sense-organ.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-stomatognathic-system.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-tissue.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/mesh-urogenital-system.belanno" />
        <idx:annotationdefinition idx:resourceLocation="http://resource.belframework.org/belframework/1.0/annotation/species-taxonomy-id.belanno" />
    </idx:annotationdefinitions>

    <idx:namespaces>
        <!-- Genes, Proteins, and RNA -->
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/entrez-gene-ids-hmr.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/hgnc-approved-symbols.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/mgi-approved-symbols.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/rgd-approved-symbols.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/swissprot-accession-numbers.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/swissprot-entry-names.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/affy-hg-u95av2.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/affy-hg-u133ab.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/affy-hg-u133-plus2.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/affy-mg-u74abc.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/affy-moe430ab.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/affy-mouse430-2.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/affy-mouse430a-2.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/affy-rae230ab-2.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/affy-rat230-2.belns" />

        <!-- Chemical Compounds -->
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/chebi-ids.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/chebi-names.belns" />

        <!-- Biological Processes, Pathologies, and Cellular Locations -->
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/go-biological-processes-accession-numbers.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/go-biological-processes-names.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/mesh-biological-processes.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/mesh-diseases.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/mesh-cellular-locations.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/go-cellular-component-accession-numbers.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/go-cellular-component-terms.belns" />

        <!-- Selventa Current Namespaces -->
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/selventa-named-human-protein-families.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/selventa-named-human-complexes.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/selventa-named-mouse-protein-families.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/selventa-named-mouse-complexes.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/selventa-named-rat-protein-families.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/selventa-named-rat-complexes.belns" />

        <!-- Selventa Legacy Namespaces -->
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/selventa-legacy-chemical-names.belns" />
        <idx:namespace idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/selventa-legacy-diseases.belns" />
    </idx:namespaces>

    <idx:equivalences>
        <!-- Entrez Gene Equivalence -->
        <idx:equivalence idx:resourceLocation="http://resource.belframework.org/belframework/1.0/equivalence/entrez-gene-ids-hmr.beleq.gz">
            <idx:namespace-ref idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/entrez-gene-ids-hmr.belns" />
        </idx:equivalence>

        <!-- HGNC Equivalence -->
        <idx:equivalence idx:resourceLocation="http://resource.belframework.org/belframework/1.0/equivalence/hgnc-approved-symbols.beleq.gz">
            <idx:namespace-ref idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/hgnc-approved-symbols.belns" />
        </idx:equivalence>

        <!-- MGI Equivalence -->
        <idx:equivalence idx:resourceLocation="http://resource.belframework.org/belframework/1.0/equivalence/mgi-approved-symbols.beleq.gz">
            <idx:namespace-ref idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/mgi-approved-symbols.belns" />
        </idx:equivalence>

        <!-- RGD Equivalence -->
        <idx:equivalence idx:resourceLocation="http://resource.belframework.org/belframework/1.0/equivalence/rgd-approved-symbols.beleq.gz">
            <idx:namespace-ref idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/rgd-approved-symbols.belns" />
        </idx:equivalence>

        <!-- SwissProt Accession Numbers Equivalence -->
        <idx:equivalence idx:resourceLocation="http://resource.belframework.org/belframework/1.0/equivalence/swissprot-accession-numbers.beleq.gz">
            <idx:namespace-ref idx:resourceLocation="http://resource.belframework.org/belframework/1.0/namespace/swissprot-accession-numbers.belns" />
        </idx:equivalence>
